### ISSUE TITLE
TIFF page selection

### ISSUE THREAD

**Issue by SoftExpert** [davidbyttow/govips#188] opened 2021-04-14 21:00 UTC
Govips seems to have a basic support for TIFF images.
However, an important feature is missing: the possibility to choose an arbitrary page (for the multipage tiffs) and then extract, transform or save that page. 
Libvips seems to have the necessary methods (at least based on https://github.com/libvips/libvips/issues/775).

Can this feature be easily added ?

Thank you in advance!
Best regards,
SoftExpert

**Comment by tonimelisma** [comment] 2021-04-15 18:25
Hey @SoftExpert - sure thing! This feature is actually in the works: https://github.com/davidbyttow/govips/pull/166

Perhaps you could ask davidbyttow how you could help expedite things.

**Comment by SoftExpert** [comment] 2021-04-16 07:24
Well, then, how can I help ?

**Comment by tonimelisma** [comment] 2021-04-18 10:49
@davidbyttow is there anything contributors can do to help with the import parameters PR?

**Comment by davidbyttow** [comment] 2021-04-21 16:38
Hey man, yeah I need to get this in. I think there was one outstanding bug, I'll look at this in the next day or so. Been busy at work.

**Comment by SoftExpert** [comment] 2021-06-10 15:10
Any news on this feature, please ?

**Comment by davidbyttow** [comment] 2021-06-10 21:05
Merged this just now. https://github.com/davidbyttow/govips/pull/166

**Comment by davidbyttow** [comment] 2021-06-10 21:06
please re-open if this isn't working as intended

**Closed by davidbyttow** 2021-06-10 21:06 UTC
